#!/bin/bash

# get user input
echo Let\'s Post Hard!
printf Title:\ 
read title
# file extension is lower skewer case, no special characters, max 40 characters
extension=$(echo $title | tr -dc '[:alnum:]\n\r ' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | cut -c -40)

# make dir
cd content/blog
mkdir $extension
cd $extension

# make markdown
touch index.md
echo "---" >> index.md
echo "title: $title" >> index.md
echo "author: $MYNAME" >> index.md
DATE=$(date +%FT%T)
echo "date: $DATE" >> index.md
echo "---" >> index.md

vim index.md

printf Publish\ changes\?\ [Y/n]\ 
read answer
if [ $answer = Y ]
then
  # commit the new post
  cd ../../../
  git add .
  git commit -m "$MYNAME wrote '$title'"
  git push
fi