#!/bin/bash

# get user input
echo Let\'s Post Hard!
printf URL\ Extension:\ 
read extension
printf Title:\ 
read title

# make dir
cd content/blog
mkdir $extension
cd $extension

# make markdown
touch index.md
echo "---" >> index.md
echo "title: $title" >> index.md
echo "author: $MYNAME" >> index.md
DATE=$(date +%F)
echo "date: $DATE" >> index.md
echo "---" >> index.md